import type { Adjunto, EnvioProvincia, Pedido } from "./dominio";

/* Este archivo dejó de ser el origen de datos de la app en la Fase 3 y ahora solo
   alimenta `scripts/gen-seed.cjs`. La semilla no trae los campos que la base
   deriva o resuelve por join (`tieneComprobante`, los ids del ubigeo), así que se
   escriben fuera del tipo `Pedido` en vez de inventarlos aquí. */
type PedidoSemilla = Omit<Pedido, "responsableId" | "tieneComprobante" | "envio" | "adjuntos"> & {
  envio?: Omit<EnvioProvincia, "departamentoId" | "provinciaId">;
  // El id del adjunto lo pone Postgres al sembrar, igual que el del pedido.
  adjuntos: Omit<Adjunto, "id">[];
};

/** Fecha de referencia del prototipo: define qué está vencido y qué vence hoy. */
export const HOY = "2026-08-29";

const sinHistorial = (creado: string, estado: Pedido["estado"]): Pedido["historial"] => {
  const base: Pedido["historial"] = [
    {
      estado: "registrado",
      usuario: "Ana Torres",
      rol: "administracion",
      fecha: `${creado}T08:30:00`,
    },
  ];
  if (estado !== "registrado") {
    base.push({
      estado,
      usuario: "Miguel Ruiz",
      rol: "operaciones",
      fecha: `${creado}T16:05:00`,
    });
  }
  return base;
};

export const PEDIDOS: PedidoSemilla[] = [
  {
    codigo: "LCL_2026_H4TP",
    cliente: "Corporación Andina SAC",
    telefonoCliente: "981 342 705",
    tipos: ["CL"],
    producto: null,
    cantidad: 12,
    estado: "en_proceso",
    ubicacion: "taller",
    entrega: "tienda",
    fechaPrometida: "2026-08-30",
    fechaCreacion: "2026-08-24",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 1250,
    montoPagado: 600,
    responsable: "Angel",
    detalle: "12 placas 60x40 en acrílico transparente 3mm, grabado del logo al centro.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "plano-corte-v2.pdf", peso: "840 KB" },
      { tipo: "diseno", nombre: "referencia-cliente.jpg", peso: "1.2 MB" },
    ],
    abonos: [{ fecha: "2026-08-24", monto: 600, metodo: "efectivo", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-24", "en_proceso"),
    auditoria: [],
  },
  {
    codigo: "LPT_2026_K9ZM",
    cliente: "Botica Salud Norte",
    telefonoCliente: "944 618 230",
    tipos: ["PT"],
    producto: "displays",
    cantidad: 4,
    estado: "listo",
    ubicacion: "tienda",
    entrega: "tienda",
    fechaPrometida: "2026-08-29",
    fechaCreacion: "2026-08-20",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 890,
    montoPagado: 890,
    responsable: "Isaac",
    detalle: "4 displays de mostrador, 3 niveles, acrílico blanco 4mm.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "plano-display.pdf", peso: "620 KB" },
      { tipo: "diseno", nombre: "referencia-cliente.jpg", peso: "1.1 MB" },
      { tipo: "foto_entrega", nombre: "producto-terminado.jpg", peso: "2.1 MB" },
    ],
    abonos: [{ fecha: "2026-08-20", monto: 890, metodo: "transferencia", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-20", "listo"),
    auditoria: [],
  },
  {
    codigo: "PCM_2026_R2WQ",
    cliente: "Distribuidora Chan Chan EIRL",
    telefonoCliente: "962 507 481",
    tipos: ["CM"],
    producto: null,
    cantidad: 30,
    estado: "en_transito",
    ubicacion: "agencia",
    entrega: "agencia",
    fechaPrometida: "2026-09-02",
    fechaCreacion: "2026-08-18",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 2340,
    montoPagado: 1170,
    responsable: "Juan",
    detalle: "Corte manual de 30 planchas 1.20x0.80, bordes pulidos.",
    observaciones: null,
    numeroComprobante: "F001-004512",
    esProvincia: true,
    envio: {
      departamento: "La Libertad",
      provincia: "Trujillo",
      agencia: "Shalom - Trujillo Centro",
      personaQueRecoge: "Marisol Vega Ríos",
      tipoDocumento: "DNI",
      numeroDocumento: "44821903",
      telefono: "958 447 210",
      montoFlete: 120,
      fletePagado: true,
      observacionesEnvio: "Avisar a la persona que recoge una hora antes de la llegada.",
    },
    adjuntos: [
      { tipo: "diseno", nombre: "plano-corte-v2.pdf", peso: "840 KB" },
      { tipo: "diseno", nombre: "referencia-cliente.jpg", peso: "1.2 MB" },
      { tipo: "factura", nombre: "factura-F001-004512.pdf", peso: "210 KB" },
      { tipo: "guia", nombre: "guia-remision.pdf", peso: "180 KB" },
    ],
    abonos: [
      { fecha: "2026-08-18", monto: 1000, metodo: "transferencia", usuario: "Ana Torres" },
      { fecha: "2026-08-25", monto: 170, metodo: "yape_plin", usuario: "Ana Torres" },
    ],
    historial: [
      { estado: "registrado", usuario: "Ana Torres", rol: "administracion", fecha: "2026-08-18T09:14:00" },
      { estado: "en_proceso", usuario: "Ana Torres", rol: "administracion", fecha: "2026-08-19T08:02:00" },
      { estado: "listo", usuario: "Miguel Ruiz", rol: "operaciones", fecha: "2026-08-26T17:41:00" },
      { estado: "en_transito", usuario: "Carla Díaz", rol: "logistica", fecha: "2026-08-28T11:20:00" },
    ],
    auditoria: [
      { usuario: "Carla Díaz", campo: "ubicacion_actual", anterior: "En taller", nuevo: "En agencia", fecha: "2026-08-28T11:20:00" },
      { usuario: "Carla Díaz", campo: "estado", anterior: "Listo", nuevo: "En tránsito", fecha: "2026-08-28T11:20:00" },
      { usuario: "Ana Torres", campo: "numero_comprobante", anterior: "—", nuevo: "F001-004512", fecha: "2026-08-28T10:57:00" },
      { usuario: "Miguel Ruiz", campo: "estado", anterior: "En proceso", nuevo: "Listo", fecha: "2026-08-26T17:41:00" },
      { usuario: "Ana Torres", campo: "monto_total", anterior: "2 100.00", nuevo: "2 340.00", fecha: "2026-08-21T15:03:00" },
    ],
  },
  {
    codigo: "LSP_2026_T7YX",
    cliente: "Universidad Nacional de Ingeniería",
    telefonoCliente: "918 264 933",
    tipos: ["SP"],
    producto: null,
    cantidad: 20,
    estado: "registrado",
    ubicacion: "taller",
    entrega: "taller",
    fechaPrometida: "2026-09-04",
    fechaCreacion: "2026-08-28",
    tipoPago: "credito",
    plazoCredito: 30,
    montoTotal: 4100,
    montoPagado: 0,
    responsable: null,
    detalle: "20 planchas acrílico cristal 2440x1220x5mm, sin cortar.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [],
    abonos: [],
    historial: sinHistorial("2026-08-28", "registrado"),
    auditoria: [],
  },
  {
    codigo: "PPT_2026_M3NP",
    cliente: "Clínica San Pablo - Arequipa",
    telefonoCliente: "973 155 620",
    tipos: ["PT"],
    producto: "letreros",
    cantidad: 6,
    estado: "en_proceso",
    ubicacion: "taller",
    entrega: "agencia",
    fechaPrometida: "2026-08-27",
    fechaCreacion: "2026-08-14",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 3680,
    montoPagado: 1840,
    responsable: "Clever",
    detalle: "6 letreros de señalización interna, acrílico azul 5mm con vinil blanco.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: true,
    envio: {
      departamento: "Arequipa",
      provincia: "Arequipa",
      agencia: "Olva Courier - Cercado",
      personaQueRecoge: "Jorge Cáceres Núñez",
      tipoDocumento: "DNI",
      numeroDocumento: "29874102",
      telefono: "954 118 302",
      montoFlete: 180,
      fletePagado: false,
    },
    adjuntos: [
      { tipo: "diseno", nombre: "senaletica-v3.pdf", peso: "1.4 MB" },
      { tipo: "diseno", nombre: "vinil-blanco.ai", peso: "780 KB" },
    ],
    abonos: [{ fecha: "2026-08-14", monto: 1840, metodo: "transferencia", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-14", "en_proceso"),
    auditoria: [],
  },
  {
    codigo: "LCL_2026_B8FD",
    cliente: "Restaurante El Tumi",
    telefonoCliente: null,
    tipos: ["CL"],
    producto: null,
    cantidad: 25,
    estado: "entregado",
    ubicacion: "tienda",
    entrega: "tienda",
    fechaPrometida: "2026-08-22",
    fechaCreacion: "2026-08-15",
    fechaEntrega: "2026-08-22",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 640,
    montoPagado: 640,
    responsable: "John",
    detalle: "25 porta cartas cortados a láser, acrílico ámbar 3mm.",
    observaciones: null,
    numeroComprobante: "F001-004489",
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "porta-cartas.pdf", peso: "520 KB" },
      { tipo: "factura", nombre: "factura-F001-004489.pdf", peso: "198 KB" },
    ],
    abonos: [{ fecha: "2026-08-15", monto: 640, metodo: "efectivo", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-15", "entregado"),
    auditoria: [],
  },
  {
    codigo: "LCM_2026_W5QA",
    cliente: "Gimnasio Bodytech Miraflores",
    telefonoCliente: "956 890 174",
    tipos: ["CM"],
    producto: null,
    cantidad: 8,
    estado: "observado",
    motivo: "El cliente no confirma la medida de altura; producción detenida desde el 26/08.",
    ubicacion: "taller",
    entrega: "domicilio",
    direccion: "Av. Benavides 1944, Miraflores",
    fechaPrometida: "2026-08-28",
    fechaCreacion: "2026-08-21",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 1480,
    montoPagado: 400,
    responsable: "Angel",
    detalle: "Separadores de vestuario. FALTA que el cliente confirme la altura final.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [{ tipo: "diseno", nombre: "separadores-v1.pdf", peso: "910 KB" }],
    abonos: [{ fecha: "2026-08-21", monto: 400, metodo: "yape_plin", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-21", "observado"),
    auditoria: [],
  },
  {
    codigo: "PCL_2026_J2VH",
    cliente: "Municipalidad de Huancayo",
    telefonoCliente: "949 302 668",
    tipos: ["CL"],
    producto: null,
    cantidad: 40,
    estado: "listo",
    ubicacion: "taller",
    entrega: "agencia",
    fechaPrometida: "2026-08-31",
    fechaCreacion: "2026-08-19",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 5250,
    montoPagado: 2625,
    responsable: "Juan",
    detalle: "40 placas conmemorativas grabadas a láser, acrílico bronce 4mm.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: true,
    envio: {
      departamento: "Junín",
      provincia: "Huancayo",
      agencia: "Transportes Molina",
      personaQueRecoge: "Elsa Quispe Ramos",
      tipoDocumento: "DNI",
      numeroDocumento: "20114588",
      telefono: "964 220 118",
      montoFlete: 260,
      fletePagado: false,
    },
    adjuntos: [
      { tipo: "diseno", nombre: "placa-conmemorativa.pdf", peso: "1.1 MB" },
      { tipo: "diseno", nombre: "escudo-municipal.svg", peso: "96 KB" },
    ],
    abonos: [{ fecha: "2026-08-19", monto: 2625, metodo: "transferencia", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-19", "listo"),
    auditoria: [],
  },
  {
    codigo: "LPT_2026_N6XC",
    cliente: "Óptica Visión Lima",
    telefonoCliente: "967 471 052",
    tipos: ["PT"],
    producto: "porta_afiches",
    cantidad: 10,
    estado: "en_proceso",
    ubicacion: "taller",
    entrega: "tienda",
    fechaPrometida: "2026-09-01",
    fechaCreacion: "2026-08-25",
    tipoPago: "credito",
    plazoCredito: 15,
    montoTotal: 720,
    montoPagado: 0,
    responsable: "Isaac",
    detalle: "10 porta afiches A3 vertical de pared, cristal 3mm.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [{ tipo: "diseno", nombre: "porta-afiche-a3.pdf", peso: "440 KB" }],
    abonos: [],
    historial: sinHistorial("2026-08-25", "en_proceso"),
    auditoria: [],
  },
  {
    codigo: "LCL_2026_D9KR",
    cliente: "Colegio Los Álamos",
    telefonoCliente: "921 736 480",
    tipos: ["CL"],
    producto: null,
    cantidad: 60,
    estado: "registrado",
    ubicacion: "taller",
    entrega: "taller",
    fechaPrometida: "2026-09-05",
    fechaCreacion: "2026-08-28",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 1980,
    montoPagado: 990,
    responsable: null,
    detalle: "Set de 60 medallas cortadas a láser con nombre grabado.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "medallas-nombres.xlsx", peso: "48 KB" },
      { tipo: "diseno", nombre: "troquel-medalla.pdf", peso: "310 KB" },
    ],
    abonos: [{ fecha: "2026-08-28", monto: 990, metodo: "efectivo", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-28", "registrado"),
    auditoria: [],
  },
  {
    codigo: "PSP_2026_G3LM",
    cliente: "Ferretería El Sol - Piura",
    telefonoCliente: "988 204 619",
    tipos: ["SP"],
    producto: null,
    cantidad: 30,
    estado: "entregado",
    ubicacion: "agencia",
    entrega: "agencia",
    fechaPrometida: "2026-08-20",
    fechaCreacion: "2026-08-08",
    fechaEntrega: "2026-08-20",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 6300,
    montoPagado: 6300,
    responsable: "Clever",
    detalle: "30 planchas de acrílico blanco 3mm.",
    observaciones: null,
    numeroComprobante: "F001-004470",
    esProvincia: true,
    envio: {
      departamento: "Piura",
      provincia: "Piura",
      agencia: "Shalom - Piura",
      personaQueRecoge: "Luis Farfán Castro",
      tipoDocumento: "DNI",
      numeroDocumento: "03887219",
      telefono: "969 553 017",
      montoFlete: 340,
      fletePagado: true,
    },
    adjuntos: [
      { tipo: "factura", nombre: "factura-F001-004470.pdf", peso: "205 KB" },
      { tipo: "guia", nombre: "guia-remision-piura.pdf", peso: "176 KB" },
    ],
    abonos: [{ fecha: "2026-08-08", monto: 6300, metodo: "transferencia", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-08", "entregado"),
    auditoria: [],
  },
  {
    codigo: "LPT_2026_Z4BT",
    cliente: "Cevichería La Mar del Sur",
    telefonoCliente: "935 617 902",
    tipos: ["PT"],
    producto: "cajas",
    cantidad: 15,
    estado: "listo",
    ubicacion: "tienda",
    entrega: "tienda",
    fechaPrometida: "2026-08-29",
    fechaCreacion: "2026-08-22",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 1120,
    montoPagado: 560,
    responsable: "John",
    detalle: "15 cajas porta cubiertos con tapa, cristal 3mm.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "caja-cubiertos.pdf", peso: "380 KB" },
      { tipo: "foto_entrega", nombre: "muestra-aprobada.jpg", peso: "1.8 MB" },
    ],
    abonos: [{ fecha: "2026-08-22", monto: 560, metodo: "efectivo", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-22", "listo"),
    auditoria: [],
  },
  {
    codigo: "LCM_2026_Q7SE",
    cliente: "Estudio Contable Paredes",
    telefonoCliente: "974 083 251",
    tipos: ["CM"],
    producto: null,
    cantidad: 6,
    estado: "anulado",
    motivo: "Cliente canceló el pedido el 23/08 por cambio de proveedor.",
    ubicacion: "taller",
    entrega: "tienda",
    fechaPrometida: "2026-08-26",
    fechaCreacion: "2026-08-17",
    fechaAnulacion: "2026-08-23",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 430,
    montoPagado: 0,
    responsable: null,
    detalle: "Porta tarjetas de escritorio.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [],
    abonos: [],
    historial: sinHistorial("2026-08-17", "anulado"),
    auditoria: [],
  },
  {
    codigo: "PCL_2026_V8HN",
    cliente: "Hotel Casa Andina - Cusco",
    telefonoCliente: "913 590 447",
    tipos: ["CL"],
    producto: null,
    cantidad: 48,
    estado: "registrado",
    ubicacion: "taller",
    entrega: "agencia",
    fechaPrometida: "2026-09-08",
    fechaCreacion: "2026-08-27",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 2870,
    montoPagado: 1000,
    responsable: null,
    detalle: "Señalética de habitaciones, 48 piezas grabadas a láser.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: true,
    envio: {
      departamento: "Cusco",
      provincia: "Cusco",
      agencia: null,
      personaQueRecoge: null,
      tipoDocumento: "DNI",
      numeroDocumento: null,
      telefono: null,
      montoFlete: 0,
      fletePagado: false,
    },
    adjuntos: [{ tipo: "diseno", nombre: "numeracion-habitaciones.pdf", peso: "660 KB" }],
    abonos: [{ fecha: "2026-08-27", monto: 1000, metodo: "transferencia", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-27", "registrado"),
    auditoria: [],
  },
  {
    codigo: "LPT_2026_C2RJ",
    cliente: "Farmacia Vida Sana",
    telefonoCliente: null,
    tipos: ["PT"],
    producto: "pivotante",
    cantidad: 2,
    estado: "en_proceso",
    ubicacion: "taller",
    entrega: "domicilio",
    direccion: "Jr. Huánuco 455, Cercado de Lima",
    fechaPrometida: "2026-08-31",
    fechaCreacion: "2026-08-26",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 1560,
    montoPagado: 780,
    responsable: "Angel",
    detalle: "2 exhibidores pivotantes de piso, 5 caras.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "pivotante-5-caras.pdf", peso: "1.3 MB" },
      { tipo: "diseno", nombre: "render-cliente.png", peso: "2.4 MB" },
    ],
    abonos: [{ fecha: "2026-08-26", monto: 780, metodo: "yape_plin", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-26", "en_proceso"),
    auditoria: [],
  },
  {
    codigo: "LCL_2026_F5PW",
    cliente: "Banco Pichincha - Ag. San Isidro",
    telefonoCliente: "968 725 130",
    tipos: ["CL"],
    producto: null,
    cantidad: 8,
    estado: "entregado",
    ubicacion: "tienda",
    entrega: "tienda",
    fechaPrometida: "2026-08-25",
    fechaCreacion: "2026-08-13",
    fechaEntrega: "2026-08-25",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 2240,
    montoPagado: 2240,
    responsable: "Juan",
    detalle: "Mamparas divisorias de ventanilla, 8 unidades.",
    observaciones: null,
    numeroComprobante: "F001-004501",
    esProvincia: false,
    adjuntos: [
      { tipo: "diseno", nombre: "mampara-ventanilla.pdf", peso: "740 KB" },
      { tipo: "foto_entrega", nombre: "instalacion-final.jpg", peso: "2.6 MB" },
      { tipo: "factura", nombre: "factura-F001-004501.pdf", peso: "212 KB" },
    ],
    abonos: [{ fecha: "2026-08-13", monto: 2240, metodo: "transferencia", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-13", "entregado"),
    auditoria: [],
  },
  /* ── Pedidos que ejercitan el modelo nuevo ── */
  {
    // Pedido combinado: corte láser + accesorios. Por eso su código lleva "MX".
    codigo: "LMX_2026_A7KD",
    cliente: "Cafetería Bisetti",
    telefonoCliente: "942 318 906",
    tipos: ["CL", "AC"],
    producto: null,
    cantidad: 18,
    estado: "en_proceso",
    ubicacion: "taller",
    entrega: "tienda",
    fechaPrometida: "2026-09-03",
    fechaCreacion: "2026-08-27",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 2150,
    montoPagado: 900,
    responsable: "Isaac",
    detalle: "12 posavasos grabados y 6 soportes de menú con bisagra de aluminio.",
    observaciones: "El cliente pasa a revisar la muestra el lunes por la mañana.",
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [{ tipo: "diseno", nombre: "posavasos-logo.pdf", peso: "410 KB" }],
    abonos: [{ fecha: "2026-08-27", monto: 900, metodo: "yape_plin", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-27", "en_proceso"),
    auditoria: [],
  },
  {
    // Solo planchas: la cantidad va con decimales y el detalle usa el formato sugerido.
    codigo: "LSP_2026_H2QN",
    cliente: "Vidriería Santa Rosa",
    telefonoCliente: "957 604 283",
    tipos: ["SP"],
    producto: null,
    cantidad: 2.5,
    estado: "registrado",
    ubicacion: "tienda",
    entrega: "taller",
    fechaPrometida: "2026-09-01",
    fechaCreacion: "2026-08-29",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 780,
    montoPagado: 780,
    responsable: null,
    detalle: "2.5 Acrílico Alfa 5mm transparente F7",
    observaciones: "Media plancha se corta del retazo de la semana pasada.",
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [],
    abonos: [{ fecha: "2026-08-29", monto: 780, metodo: "efectivo", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-29", "registrado"),
    auditoria: [],
  },
  {
    // Cerrado hoy: sigue apareciendo en la vista de pedidos hasta mañana.
    codigo: "LCL_2026_Y3MB",
    cliente: "Panadería San Jorge",
    telefonoCliente: "929 861 375",
    tipos: ["CL"],
    producto: null,
    cantidad: 30,
    estado: "entregado",
    ubicacion: "tienda",
    entrega: "tienda",
    fechaPrometida: "2026-08-29",
    fechaCreacion: "2026-08-24",
    fechaEntrega: "2026-08-29",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 510,
    montoPagado: 510,
    responsable: "John",
    detalle: "30 porta precios de mostrador, cristal 2mm.",
    observaciones: null,
    numeroComprobante: "F001-004520",
    esProvincia: false,
    adjuntos: [{ tipo: "factura", nombre: "factura-F001-004520.pdf", peso: "194 KB" }],
    abonos: [{ fecha: "2026-08-24", monto: 510, metodo: "efectivo", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-08-24", "entregado"),
    auditoria: [],
  },
  {
    // Anulado hoy: mismo caso que el anterior, por la otra vía de cierre.
    codigo: "LCM_2026_X9TR",
    cliente: "Boutique Almendra",
    telefonoCliente: "983 240 517",
    tipos: ["CM"],
    producto: null,
    cantidad: 4,
    estado: "anulado",
    motivo: "El cliente canceló hoy: la tienda no abre en la fecha prevista.",
    ubicacion: "taller",
    entrega: "tienda",
    fechaPrometida: "2026-09-06",
    fechaCreacion: "2026-08-26",
    fechaAnulacion: "2026-08-29",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 690,
    montoPagado: 0,
    responsable: null,
    detalle: "4 exhibidores de vitrina, acrílico blanco 3mm.",
    observaciones: null,
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [],
    abonos: [],
    historial: sinHistorial("2026-08-26", "anulado"),
    auditoria: [],
  },
  {
    /* ── Archivo: cerrados hace semanas. Solo se encuentran en el historial. ── */
    codigo: "PCL_2026_L4WD",
    cliente: "Municipalidad de Tarapoto",
    telefonoCliente: "916 452 738",
    tipos: ["CL"],
    producto: null,
    cantidad: 55,
    estado: "entregado",
    ubicacion: "agencia",
    entrega: "agencia",
    fechaPrometida: "2026-07-20",
    fechaCreacion: "2026-07-06",
    fechaEntrega: "2026-07-18",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 7420,
    montoPagado: 7420,
    responsable: "Juan",
    detalle: "55 placas de señalización institucional grabadas a láser.",
    observaciones: null,
    numeroComprobante: "F001-004312",
    esProvincia: true,
    envio: {
      departamento: "San Martín",
      provincia: "San Martín",
      agencia: "Shalom - Tarapoto",
      personaQueRecoge: "Rocío Panduro Silva",
      tipoDocumento: "DNI",
      numeroDocumento: "01128744",
      telefono: "942 771 306",
      montoFlete: 410,
      fletePagado: true,
    },
    adjuntos: [{ tipo: "factura", nombre: "factura-F001-004312.pdf", peso: "201 KB" }],
    abonos: [
      { fecha: "2026-07-06", monto: 3710, metodo: "transferencia", usuario: "Ana Torres" },
      { fecha: "2026-07-18", monto: 3710, metodo: "transferencia", usuario: "Ana Torres" },
    ],
    historial: sinHistorial("2026-07-06", "entregado"),
    auditoria: [],
  },
  {
    codigo: "LPT_2026_S6VK",
    cliente: "Hostal Miraflores Suites",
    telefonoCliente: "961 073 894",
    tipos: ["PT"],
    producto: "letreros",
    cantidad: 22,
    estado: "entregado",
    ubicacion: "tienda",
    entrega: "tienda",
    fechaPrometida: "2026-08-01",
    fechaCreacion: "2026-07-21",
    fechaEntrega: "2026-07-30",
    tipoPago: "contado",
    plazoCredito: null,
    montoTotal: 1890,
    montoPagado: 1890,
    responsable: "Angel",
    detalle: "22 letreros de puerta con numeración, acrílico negro 4mm.",
    observaciones: null,
    numeroComprobante: "B001-000318",
    esProvincia: false,
    adjuntos: [
      { tipo: "factura", nombre: "boleta-B001-000318.pdf", peso: "188 KB" },
      { tipo: "foto_entrega", nombre: "letreros-instalados.jpg", peso: "2.2 MB" },
    ],
    abonos: [{ fecha: "2026-07-21", monto: 1890, metodo: "tarjeta", usuario: "Ana Torres" }],
    historial: sinHistorial("2026-07-21", "entregado"),
    auditoria: [],
  },
  {
    codigo: "LCM_2026_B3ZQ",
    cliente: "Imprenta Del Valle",
    telefonoCliente: "937 528 160",
    tipos: ["CM", "AC"],
    producto: null,
    cantidad: 12,
    estado: "anulado",
    motivo: "Se anuló el 24/07: el material llegó rayado y el cliente prefirió no reprogramar.",
    ubicacion: "taller",
    entrega: "tienda",
    fechaPrometida: "2026-07-29",
    fechaCreacion: "2026-07-15",
    fechaAnulacion: "2026-07-24",
    tipoPago: "a_cuenta",
    plazoCredito: null,
    montoTotal: 1340,
    montoPagado: 0,
    responsable: null,
    detalle: "12 bandejas apilables con topes de aluminio.",
    observaciones: "El adelanto se devolvió en efectivo el mismo día.",
    numeroComprobante: null,
    esProvincia: false,
    adjuntos: [],
    abonos: [],
    historial: sinHistorial("2026-07-15", "anulado"),
    auditoria: [],
  },
];

export const DEPARTAMENTOS = [
  "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco",
  "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto",
  "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali",
] as const;
